name: Runner testing
on: push

jobs:
  runner-testing:
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    - name: Bundle javascript
      id: bundle-js
      #if: steps.identify-changes.outputs.sources == 'true'
      run: |
        npm install
        sbt test
        echo "test1"
        echo "test2"
        sbt --error --batch "print publicProd"
        echo "test3"
        echo "test4"
        npm run build
